name: Android Release

on:
  push:
    branches:
      - 'main'
 
  pull_request:
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: 'gradle'
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
          cache: true

      - name: Write .env
        run: echo '{{ secrets.APP_ENV }}' > .env
  
      - name: Get dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Start release apk
        run: flutter build apk

      - name: Start release appbundle
        run: flutter build appbundle
