name: CI

on:
  push:
    branches:
      - 'main'
      - 'develop'
 
  pull_request:
    branches:
      - 'main'
      - 'develop'


jobs:
  flutter_test:
    name: Running tests
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: 'gradle'
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
          cache: true

      - name: Create .env file
        run: echo "" >> .env

      - name: Get dependencies
        run: flutter pub get

      - name: Run analyze
        run: flutter analyze

      - name: Check formatting files folder lib/
        run: flutter format --dry-run --set-exit-if-changed lib/
      
      - name: Check formatting files folder test/
        run: flutter format --dry-run --set-exit-if-changed test/

      - name: Check test coverage
        run: flutter test --coverage

      - name: Generate file with test coverage
        run: flutter test --machine > test-result.json

      - name: Test report
        uses: dorny/test-reporter@v1
        with:
          name: Flutter test results
          path: test-result.json
          reporter: flutter-json
      
      - uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          min_coverage: 70