name: CI/CD

on:
  # Ações e branches em que devo rodar o CI
  push:
    tags:
      - v*

  workflow_dispatch:

jobs:
  flutter_test:
    name: Run analyze and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: 'gradle'
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Run analyze
        run: flutter analyze

      - name: Check formatting files folder lib/
        run: flutter format --dry-run --set-exit-if-changed lib/
      
      - name: Check formatting files folder test/
        run: flutter format --dry-run --set-exit-if-changed test/

      - name: Check test coverage
        run: flutter test --coverage

      - name: Generate file with test coverage
        run: flutter test --machine > test-result.json

      - uses: dorny/test-reporter@v1.4.2
        with:
          name: test-results
          path: test-results.json
          reporter: flutter-json
      
      - uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          min_covarage: 100

  build_android:
    name: Build android
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: 'gradle'
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
          cache: true

      - name: Write .env
        run: echo '{{ secrets.APP_ENV }}' > .env
  
      - name: Get dependencies
        run: flutter pub get

      - name: Start release apk
        run: flutter build apk

      - name: Start release appbundle
        run: flutter build appbundle

      - name: Upload apk
        uses: actions/upload-artifact@v2.1.4
        with:
          name: apk
          path: build/app/outputs/apk/release/app-release.apk

  build_ios:
    name: Build iOS
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: '3.7.7'
          architecture: x64
      
      - name: Get dependencies
        run: flutter pub get

      - name: Start release ios
        run: flutter build ios --release --no-codesign


